FORMAT: 1A

# raiapi

RaiPlay API to retrieve tv program information and files for the past seven days

## Canali Collection [/canali]

### List All Canali [GET]

Lists all the available channels

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": 0,
                "name": "RaiUno"
            }
        ]

## Programmi Collection [/canali/{canaleId}/programmi]

### List All Programmi [GET]

Lists available programs given a channel

+ Parameters
    + canaleId: `0` (int) - Canale ID

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": 0,
                "name": "TG1 NOTTE"
            }
        ]

## Qualità Collection [/canali/{canaleId}/programmi/{programmaId}/qualita]

### List All Qualità [GET]

Lists available quality for a given program

+ Parameters
    + canaleId: `0` (int) - Canale ID
    + programmaId: `0` (int) - Programma ID

+ Response 200 (application/json; charset=utf-8)

        [
            {
                "id": 0,
                "name": "h264 800"
            },
            {
                "id": 1,
                "name": "h264 1200"
            },
            {
                "id": 2,
                "name": "h264 1800"
            }
        ]
        
## File URL [/canali/{canaleId}/programmi/{programmaId}/qualita/{qualitaId}/url]

### Get URL [GET]

Gets video file URL

+ Parameters
    + canaleId: `0` (int) - Canale ID
    + programmaId: `0` (int) - Programma ID
    + qualitaId: `0` (int) - Qualita ID

+ Response 200 (application/json; charset=utf-8)

        {
            "url": "http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4"
        }
        
## File [/canali/{canaleId}/programmi/{programmaId}/qualita/{qualitaId}/file]

### Get File [GET]

Redirects to te file URL

+ Parameters
    + canaleId: `0` (int) - Canale ID
    + programmaId: `0` (int) - Programma ID
    + qualitaId: `0` (int) - Qualita ID

+ Response 302

    + Headers

            Location: http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4
    + Body

            Found Redirecting to http://distribution.bbb3d.renderfarming.net/video/mp4/bbb_sunflower_1080p_30fps_normal.mp4

## RSS [/canali/{canaleId}/rss.xml]

### Get RSS [GET]

Gets video files RSS feed

+ Parameters
    + canaleId: `0` (int) - Canale ID

+ Response 200 (text/xml; charset=utf-8)

    + Headers

            Cache-Control: public, max-age=86400
    + Body

            <rss version="2.0" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:atom="http://www.w3.org/2005/Atom">
                <channel>
                    <title>Rai API - RaiUno</title>
                    <description>Rai API RSS feed for RaiUno</description>
                    <generator>raiapi.js</generator>
                    <link>https://localhost</link>
                    <language>it-IT</language>
                    <copyright>(c) 2016 localhost</copyright>
                    <atom:link href="https://localhost/canali/0/rss.xml" rel="self" type="application/rss+xml" />
                </channel>
            </rss>
