name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set env vars
      run: |
        echo VERSION_NUMBER=$(jq -r < package.json .version) >> $GITHUB_ENV
        echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
        git log --no-merges --format='- %s' $(git log --merges --format='%H' -n 2)..HEAD -- >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV
    - name: Create release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        release_name: ${{ env.VERSION_NUMBER }}
        tag: ${{ env.VERSION_NUMBER }}
        overwrite: true
        body: ${{ env.RELEASE_NOTES }}
